#sample makefile script
CC = gcc
CFLAGS = -Wall -o2 -DSHAOLEI -ggdb
LFALGS = -lpthread -lm
SRCS = data_structure.c game.c map.c shaolei.c show_map.c
EXEC = shaolei

all:
	$(CC) $(SRC) $(SRCS) -o $(EXEC) $(LFLAGS)

clean:
	rm -rf *.o
